app_users/urls.py
from django.urls import path
from . import views

#urlpatterns = [
#	path('' , views.index, name= 'index')
#]

#from django.urls import path
#from app_users import views


# app_name = 'app_users'
urlpatterns = [
    path('',views.HomeView.as_view(),name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('contact/', views.ContactView.as_view(), name="contact"),
]

curriculum/urls.py
from django.urls import path
from . import views

app_name='curriculum'
urlpatterns = [
    path('', views.StandardListView.as_view(), name='standard_list'),
    path('<slug:slug>/', views.SubjectListView.as_view(), name='subject_list'),
    path('<str:standard>/<slug:slug>/', views.LessonListView.as_view(), name='lesson_list'),
    path('<str:standard>/<str:slug>/create/', views.LessonCreateView.as_view(),name='lesson_create'),
    path('<str:standard>/<str:subject>/<slug:slug>/', views.LessonDetailView.as_view(),name='lesson_detail'),
    path('<str:standard>/<str:subject>/<slug:slug>/update/', views.LessonUpdateView.as_view(),name='lesson_update'),
    path('<str:standard>/<str:subject>/<slug:slug>/delete/', views.LessonDeleteView.as_view(),name='lesson_delete'),

]

teaching_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import app_users
import curriculum

urlpatterns = [
    path('', include('app_users.urls')),
    path('curriculum/',include('curriculum.urls')),
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
                                                       

curriculum/models.py
#from django.db import models

# Create your models here.


from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
import os

# Create your models here.
class Standard(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

def save_subject_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.subject_id:
        filename = 'Subject_Pictures/{}.{}'.format(instance.subject_id, ext)
    return os.path.join(upload_to, filename)

class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE, related_name='subjects')
    image = models.ImageField(upload_to=save_subject_image, blank=True, verbose_name='Subject Image')
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)


def save_lesson_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.lesson_id:
        filename = 'lesson_files/{}/{}.{}'.format(instance.lesson_id,instance.lesson_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.lesson_id) + str('1')
            filename =  'lesson_images/{}/{}.{}'.format(instance.lesson_id,new_name, ext)
    return os.path.join(upload_to, filename)

class Lesson(models.Model):
    lesson_id = models.CharField(max_length=100, unique=True)
    Standard = models.ForeignKey(Standard, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='lessons')
    name = models.CharField(max_length=250)
    position = models.PositiveSmallIntegerField(verbose_name="Chapter no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_lesson_files,verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_lesson_files,verbose_name="Presentations", blank=True)
    Notes = models.FileField(upload_to=save_lesson_files,verbose_name="Notes", blank=True)

    class Meta:
        ordering = ['position']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('curriculum:lesson_list', kwargs={'slug':self.subject.slug, 'standard':self.Standard.slug})

class WorkingDays(models.Model):
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_days')
    day = models.CharField(max_length=100)
    def __str__(self):
        return self.day

class TimeSlots(models.Model):
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_time_slots')
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return str(self.start_time) + ' - ' + str(self.end_time) 

class SlotSubject(models.Model):
    standard = models.ForeignKey(Standard, on_delete=models.CASCADE,related_name='standard_slots')
    day = models.ForeignKey(WorkingDays, on_delete=models.CASCADE,related_name='standard_slots_days')
    slot = models.ForeignKey(TimeSlots, on_delete=models.CASCADE,related_name='standard_slots_time')
    slot_subject = models.ForeignKey(Subject, on_delete=models.CASCADE,related_name='standard_slots_subject')

    def __str__(self):
        return str(self.standard)+ ' - ' + str(self.day) + ' - ' + str(self.slot) + ' - ' + str(self.slot_subject)

class Comment(models.Model):
    lesson_name = models.ForeignKey(Lesson,null=True, on_delete=models.CASCADE,related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("Comment", null=True, blank=True, on_delete=models.CASCADE,related_name='replies')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

curriculum/forms.py
from django import forms
from .models import Comment, Reply, Lesson

class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ('lesson_id','name','position','video','ppt','Notes')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

curriculum/views.py
#from django.shortcuts import render

# Create your views here.

from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView,
                                    ListView, CreateView,
                                    UpdateView,DeleteView,FormView,)
from .models import Standard, Subject, Lesson, Comment, WorkingDays, TimeSlots
from django.urls import reverse_lazy
from .forms import CommentForm,ReplyForm, LessonForm
from django.http import HttpResponseRedirect



class StandardListView(ListView):
    context_object_name = 'standards'
    model = Standard
    template_name = 'curriculum/standard_list_view.html'

class SubjectListView(DetailView):
    context_object_name = 'standards'
    extra_context = {
        'slots': TimeSlots.objects.all()
    }
    model = Standard
    template_name = 'curriculum/subject_list_view.html'

class LessonListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'curriculum/lesson_list_view.html'

class LessonDetailView(DetailView, FormView):
    context_object_name = 'lessons'
    model = Lesson
    template_name = 'curriculum/lesson_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)


    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_detail',kwargs={'standard':standard.slug,
                                                             'subject':subject.slug,
                                                             'slug':self.object.slug})
    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.lesson_name = self.object.comments.name
        fm.lesson_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class LessonCreateView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = LessonForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'curriculum/lesson_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        standard = self.object.standard
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug,
                                                             'slug':self.object.slug})


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Standard = self.object.standard
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class LessonUpdateView(UpdateView):
    fields = ('name','position','video','ppt','Notes')
    model= Lesson
    template_name = 'curriculum/lesson_update.html'
    context_object_name = 'lessons'

class LessonDeleteView(DeleteView):
    model= Lesson
    context_object_name = 'lessons'
    template_name = 'curriculum/lesson_delete.html'

    def get_success_url(self):
        print(self.object)
        standard = self.object.Standard
        subject = self.object.subject
        return reverse_lazy('curriculum:lesson_list',kwargs={'standard':standard.slug,'slug':subject.slug})
        

curriculum/templates/curriculum/lesson_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Lesson Delete {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Deletion </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Delete</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Delete {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>

<h3 class="mb-4" style="color:#ff5722;">Are you sure you want to delete {{lessons.name}} chapter?</h3>

<form method="post">
  {% csrf_token %}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Delete" class="btn btn-danger btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-block">Cancel Deletion</a>
        </div>
  </div>
</form>

{% endblock %}

curriculum/templates/curriculum/lesson_detail_view.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{lessons.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Chapter-{{lessons.position}}: {{lessons.name}}</h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li class="disabled-text" >{{lessons.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Lecture Details</h2>
    <div class="row d-flex justify-content-center mb-3">
      <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">Created on {{lessons.created_at}} by <cite title="Source Title">{{lessons.created_by}}</cite></footer>
        </blockquote>
    </div>
    <!-- video -->
    <div class="row d-flex justify-content-center mb-3">
      <div id="player-overlay">
            <video controls>
                <source src="{{lessons.video.url}}"  type="video/mp4">
              </video>
      </div>
    </div>
    <!-- download cards -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
      <!-- download presentations -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Presentations</h5>
                      {% if lessons.ppt %}
                      <p class="card-text">Download presentations from the lecture</p>
                      <a href="{{lessons.ppt.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                      {% else %}
                      <p class="card-text" > No PPT available</p>
                      {% endif %}

                    </div>
                  </div>
                </div>
      <!-- download notes -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Notes</h5>
                      {% if lessons.Notes %}
                      <p class="card-text">Download notes from the lecture</p>
                      <a href="{{lessons.Notes.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                      {% else %}
                      <p class="card-text">Notes not available</p>
                      {%endif%}

                    </div>
                  </div>
                </div>
      <!-- download video -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Video</h5>
                      <p class="card-text">Download Video from the lecture</p>
                      <a href="{{lessons.video.url}}" download>
                      <button type="button" class="button-les"><span>Get Files</span></button>
                      </a>
                    </div>
                  </div>
                </div>
    </div>
    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
        {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
        <div class="col-md-6 mb-3 text-center">
            <a href="{% url 'curriculum:lesson_update' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-warning btn-lg mr-4 btn-block">Update Lesson</a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'curriculum:lesson_delete' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-lg mr-4 btn-block"> Delete Lesson </a>
        </div>
        {% endif %}
      </div>
</section>

<hr class="my-5" style="color:#ff5722;">

<!-- Comments section -->
<section >
    <h2 class="mb-4 mt-5 font-weight-bold" style="color:#ff5722;">Questions And Queries</h2>
    <h4 class="mt-2 font-weight-bold" style="color:#ff5722;">Post your comment or question below:</h4>
    <br><br>
    <div class="container row">
      <div class="col-md-6">
                              <form method="post">
                                    <div class="form-group">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
                                    </div>
                              </form>

      </div>
    </div>
    <div class="row">
      {% for comment in lessons.comments.all %}
      <div class="col-md-8 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="{% static 'Images/user_avatar.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                                    <h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
                                    <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="{% static 'Images/user_avatar.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->
                            <form method="post">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
                            </form>
                          </div>
                  </div>
      </div>
      {% endfor %}
    </div>


</section>

{%endblock%}

curriculum/templates/curriculum/lesson_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > {{subjects.name}} </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=subjects.standard.slug %}">{{subjects.standard}}</a></li>
            <li class="disabled-text" >{{subjects.name}}</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
              <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Dive Deeper</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8 mb-5">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3">
                {% for lesson in subjects.lessons.all %}
                <div class="col-sm-4 mb-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Chapter-{{lesson.position}}: {{lesson.name}}</h5>
                      <!-- <p class="card-text">With supporting text below as a natural lead-in to additional content.</p> -->
                      <a href="{% url 'curriculum:lesson_detail' slug=lesson.slug subject=subjects.slug standard=lesson.Standard.slug %}" >
                      <button type="button" class="button-les"><span>Get Lectures</span></button>
                      </a>
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        <div class="row d-flex justify-content-center mb-3">
          {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
           <a href="{% url 'curriculum:lesson_create' standard=subjects.standard.slug slug=subjects.slug %}"><button type="button" class="btn btn-success btn-lg btn-bloc" > Add new Lesson </button> </a>
          {% endif %}
        </div>

</section>






{%endblock%}

curriculum/templates/curriculum/lesson_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Lesson Update {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Lesson Update </h2>
        <div class="row d-flex justify-content-center text-center">
          <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'curriculum:standard_list' %}">Curriculum</a></li>
            <li><a href="{% url 'curriculum:subject_list' slug=lessons.Standard.slug %}">{{lessons.Standard.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_list' standard=lessons.Standard.slug slug=lessons.subject.slug %}">{{lessons.subject.name}}</a></li>
            <li><a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}">{{lessons.name}}</a></li>
            <li class="disabled-text" >Lesson Update</li>
          </ul>
        </div>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                  Deleniti
                  consequuntur.</h4>
  </div>
</header>
{% endblock %}


{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update {{lessons.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi voluptate
                                    hic
                                    provident nulla repellat
                                    facere esse molestiae ipsa labore porro minima quam quaerat rem, natus repudiandae debitis
                                    est
                                    sit pariatur.</p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'curriculum:lesson_detail' standard=lessons.Standard.slug subject=lessons.subject.slug slug=lessons.slug %}" class="btn btn-danger btn-block">Cancel Update</a>
        </div>
</div>
</form>

{% endblock %}